#!/usr/bin/env bash
# ==============================================================================
# release_helper.sh — Lists, inspects and creates GitHub releases following
# Semantic Versioning, with notes generated by GitHub from merged PRs.
# ==============================================================================
set -euo pipefail

usage() {
  cat << 'HELP'
Usage: release_helper.sh <command> [OPTIONS]

Commands:
  list                      List recent GitHub releases
  view <tag>                View details of a specific release
  draft-notes               Print commits since the last tag (local preview of the notes)
  create <tag> [options]    Create a release with GitHub-generated notes

Options for create:
  --target <branch|sha>     Commit to tag when the tag does not exist yet (default: default branch)
  --draft                   Create the release as a draft
  --prerelease              Mark the release as a pre-release
  --dry-run                 Print the gh command without creating anything

Tags must follow SemVer: v1.2.3 or 1.2.3 (optionally with a -pre.release suffix).
HELP
  exit "${1:-1}"
}

CMD=${1:-""}
[ -z "$CMD" ] && usage 1
shift

require_gh() {
  if ! command -v gh >/dev/null 2>&1; then
    echo "❌ Error: gh CLI is not installed or not in PATH." >&2
    exit 1
  fi
}

require_tag() {
  if [ -z "${1:-}" ]; then
    echo "❌ Error: Tag name required (e.g. release_helper.sh $CMD v1.2.0)" >&2
    exit 1
  fi
}

case "$CMD" in
  -h|--help)
    usage 0
    ;;
  list)
    require_gh
    echo "📦 Recent GitHub Releases:"
    gh release list --limit 10
    ;;
  view)
    require_tag "${1:-}"
    require_gh
    gh release view "$1"
    ;;
  draft-notes)
    LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
    if [ -n "$LAST_TAG" ]; then
      echo "📝 Commits since $LAST_TAG:"
      git log "${LAST_TAG}..HEAD" --pretty='- %s' --no-merges
    else
      echo "📝 All commits (no previous tag found):"
      git log --pretty='- %s' --no-merges
    fi
    ;;
  create)
    TAG="${1:-}"
    require_tag "$TAG"
    shift
    if ! [[ "$TAG" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]]; then
      echo "❌ Error: Tag '$TAG' is not SemVer (expected e.g. v1.2.0)." >&2
      exit 1
    fi

    GH_CMD=(gh release create "$TAG" --generate-notes --title "$TAG")
    DRY_RUN=false
    while [[ $# -gt 0 ]]; do
      case $1 in
        --target) GH_CMD+=(--target "$2"); shift 2 ;;
        --draft) GH_CMD+=(--draft); shift ;;
        --prerelease) GH_CMD+=(--prerelease); shift ;;
        --dry-run) DRY_RUN=true; shift ;;
        *) echo "Unknown option for create: $1" >&2; usage 1 ;;
      esac
    done

    if [ "$DRY_RUN" = true ]; then
      echo "🧪 [DRY RUN] Command to be executed:"
      printf "%q " "${GH_CMD[@]}"
      echo ""
      exit 0
    fi

    require_gh
    if gh release view "$TAG" >/dev/null 2>&1; then
      echo "❌ Error: Release '$TAG' already exists." >&2
      exit 1
    fi
    echo "🚀 Creating release $TAG..."
    "${GH_CMD[@]}"
    ;;
  *)
    usage 1
    ;;
esac
