#!/usr/bin/env bash
# ==============================================================================
# release_helper.sh — Helps inspect, list, and create GitLab releases & tags
# according to Semantic Versioning and Conventional Commits.
# ==============================================================================
set -euo pipefail

usage() {
  cat << 'HELP'
Usage: release_helper.sh <command> [OPTIONS]

Commands:
  list                List recent GitLab releases
  view <tag>          View details of a specific release
  create <tag>        Create a new GitLab release with autogenerated notes
  draft-notes         Generate draft release notes from git commits since last tag
HELP
  exit 1
}

CMD=${1:-""}

if [ -z "$CMD" ]; then
  usage
fi

case "$CMD" in
  list)
    echo "📦 Recent GitLab Releases:"
    glab release list
    ;;
  view)
    TAG=${2:-""}
    if [ -z "$TAG" ]; then
      echo "❌ Error: Tag name required (e.g. ./release_helper.sh view v1.2.0)" >&2
      exit 1
    fi
    glab release view "$TAG"
    ;;
  draft-notes)
    LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
    if [ -n "$LAST_TAG" ]; then
      echo "📝 Commits since $LAST_TAG:"
      git log "${LAST_TAG}..HEAD" --oneline --no-merges
    else
      echo "📝 All commits (no previous tag found):"
      git log --oneline --no-merges
    fi
    ;;
  create)
    TAG=${2:-""}
    if [ -z "$TAG" ]; then
      echo "❌ Error: Tag name required (e.g. ./release_helper.sh create v1.2.0)" >&2
      exit 1
    fi
    NOTES=$(git log "$(git describe --tags --abbrev=0 2>/dev/null || echo HEAD~10)..HEAD" --oneline --no-merges | sed 's/^[a-f0-9]* /- /' || echo "Release $TAG")
    echo "🚀 Creating release for tag $TAG..."
    glab release create "$TAG" --notes "$NOTES"
    ;;
  *)
    usage
    ;;
esac
